import { useCallback, useEffect, useRef, useState } from "react";
import { api, friendlyMessage, isApiError } from "../api/client";
import type { ExplainResponse, LabelAttribution } from "../api/types";
import { formatModelScore } from "../utils/modelScore";
import { useApp } from "../AppContext";

export interface ExplainPanelProps {
  captureId: string;
  runId?: string | null;
  positive?: string[];
  blind?: boolean;
  autoGenerate?: boolean;
}

export default function ExplainPanel({
  captureId,
  runId,
  positive = [],
  blind = false,
  autoGenerate = false,
}: ExplainPanelProps) {
  const { config } = useApp();
  const labels = config?.active_model.labels ?? [];
  const displayNames = config?.active_model.display_names ?? {};
  const enabled =
    !!config?.explain?.enabled && config.explain.methods.includes("gradcam");

  const [current, setCurrent] = useState<ExplainResponse | null>(null);
  const [showOverlay, setShowOverlay] = useState(true);
  const [busy, setBusy] = useState(false);
  const [elapsed, setElapsed] = useState(0);
  const [error, setError] = useState<string | null>(null);
  const autoGeneratedFor = useRef<string | null>(null);

  // Viewing history is read-only: show the map generated during the original
  // run (or, failing that, the newest current one) and never compute another.
  const [loaded, setLoaded] = useState(false);
  useEffect(() => {
    if (autoGenerate || blind || !enabled) return;
    let cancelled = false;
    setLoaded(false);
    void (async () => {
      try {
        const runs = (await api.listExplanations(captureId)).explanations.filter(
          (run) => run.method === "gradcam" && !run.stale
        );
        const pick =
          runs.find((run) => runId != null && run.run_id === runId) ?? runs[0];
        const result = pick
          ? await api.getExplanation(captureId, pick.explain_id)
          : null;
        if (!cancelled) setCurrent(result);
      } catch (e) {
        if (!cancelled)
          setError(isApiError(e) ? friendlyMessage(e.code, e.message) : String(e));
      } finally {
        if (!cancelled) setLoaded(true);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [autoGenerate, blind, captureId, enabled, runId]);

  const timer = useRef<number | null>(null);
  useEffect(() => {
    if (!busy) {
      if (timer.current) window.clearInterval(timer.current);
      timer.current = null;
      return;
    }
    setElapsed(0);
    timer.current = window.setInterval(
      () => setElapsed((value) => value + 1),
      1000
    );
    return () => {
      if (timer.current) window.clearInterval(timer.current);
    };
  }, [busy]);

  const runGradCam = useCallback(async () => {
    setBusy(true);
    setError(null);
    try {
      const result = await api.explain(captureId, {
        method: "gradcam",
        labels: positive.length ? positive : labels,
        run_id: runId ?? null,
      });
      setCurrent(result);
    } catch (e) {
      setError(isApiError(e) ? friendlyMessage(e.code, e.message) : String(e));
    } finally {
      setBusy(false);
    }
  }, [captureId, labels, positive, runId]);

  useEffect(() => {
    if (!autoGenerate || blind || !enabled) return;
    const resultKey = `${captureId}:${runId ?? "latest"}`;
    if (autoGeneratedFor.current === resultKey) return;
    autoGeneratedFor.current = resultKey;
    // A reloaded result page already has its map on disk: reopen it instead
    // of recomputing and storing a duplicate.
    void (async () => {
      try {
        const existing = (await api.listExplanations(captureId)).explanations.find(
          (run) =>
            run.method === "gradcam" && !run.stale && runId != null && run.run_id === runId
        );
        if (existing) {
          setCurrent(await api.getExplanation(captureId, existing.explain_id));
          return;
        }
      } catch {
        // Listing is best-effort; fall through to generating a fresh map.
      }
      await runGradCam();
    })();
  }, [autoGenerate, blind, captureId, enabled, runGradCam, runId]);

  if (!enabled) return null;

  return (
    <div className="panel explain-panel">
      <div className="spread explain-title">
        <h2>Grad-CAM</h2>
        {!blind && autoGenerate && busy ? (
          <span className="explain-progress" aria-live="polite">
            <span className="spinner" />
            Generating heatmaps… {elapsed}s
          </span>
        ) : null}
      </div>

      {blind ? <p className="muted compact-copy">Available after labels are entered.</p> : null}
      {error ? <div className="msg error mt">{error}</div> : null}

      {!autoGenerate && !blind && loaded && !current && !error ? (
        <p className="muted compact-copy">No Grad-CAM map was generated for this capture.</p>
      ) : null}

      {!blind && current ? (
        <GradCamResult
          result={current}
          displayNames={displayNames}
          showOverlay={showOverlay}
          onToggleOverlay={() => setShowOverlay((value) => !value)}
        />
      ) : null}
    </div>
  );
}

function GradCamResult({
  result,
  displayNames,
  showOverlay,
  onToggleOverlay,
}: {
  result: ExplainResponse;
  displayNames: Record<string, string>;
  showOverlay: boolean;
  onToggleOverlay: () => void;
}) {
  const positiveAttributions = result.attributions.filter(
    (attribution) => attribution.positive !== false
  );
  const negativeAttributions = result.attributions.filter(
    (attribution) => attribution.positive === false
  );

  return (
    <div className="explain-result">
      <div className="explain-result-head">
        <span className="muted">{showOverlay ? "Overlay" : "Heatmap"}</span>
        <button type="button" className="small ghost" onClick={onToggleOverlay}>
          {showOverlay ? "Show heatmap" : "Show overlay"}
        </button>
      </div>
      <AttributionGrid
        attributions={positiveAttributions}
        displayNames={displayNames}
        showOverlay={showOverlay}
      />
      {negativeAttributions.length ? (
        <details className="negative-labels">
          <summary>Negative maps ({negativeAttributions.length})</summary>
          <div className="mt">
            <AttributionGrid
              attributions={negativeAttributions}
              displayNames={displayNames}
              showOverlay={showOverlay}
            />
          </div>
        </details>
      ) : null}
    </div>
  );
}

function AttributionGrid({
  attributions,
  displayNames,
  showOverlay,
}: {
  attributions: LabelAttribution[];
  displayNames: Record<string, string>;
  showOverlay: boolean;
}) {
  return (
    <div className="attr-grid">
      {attributions.map((attribution) => (
        <AttributionCard
          key={attribution.label}
          attribution={attribution}
          displayName={displayNames[attribution.label] ?? attribution.label}
          showOverlay={showOverlay}
        />
      ))}
    </div>
  );
}

function AttributionCard({
  attribution,
  displayName,
  showOverlay,
}: {
  attribution: LabelAttribution;
  displayName: string;
  showOverlay: boolean;
}) {
  const url = showOverlay
    ? attribution.files.overlay
    : attribution.files.heatmap;
  return (
    <figure className="attr-card">
      {url ? (
        <img src={url} alt={`${displayName} Grad-CAM`} loading="lazy" />
      ) : null}
      <figcaption className="attr-head">
        <span className="attr-name">{displayName}</span>
        {typeof attribution.score === "number" ? (
          <span className="attr-score">
            <small>Model score</small>
            <strong className="score-value small">
              {formatModelScore(attribution.score)}
            </strong>
          </span>
        ) : null}
      </figcaption>
    </figure>
  );
}
